### ISSUE TITLE
pip update version

### ISSUE THREAD

**Issue by d555** [michigan-com/linkGrabber#4]
Hey guys, pypi still has the same version before `0.3.0`, and because of I'm using this package with mine `digs` I'm having troubles, please update on pip the last changes.

**Comment by neurosnap** [comment]
Greetings!  https://pypi.python.org/pypi/linkGrabber/0.3.0

Are you saying that it isn't actually 0.3.0 but the version prior?

**Comment by d555** [comment]
Yeah, sorry. The version is good, I have a misunderstanding here. 
But, it happens  that from a Windows laptop, after install `linkGrabber` and check `pip`. 
`from linkGrabber import Links` fails. I'm checking what it is happing.

**Comment by d555** [comment]
It was a problem with `pip`, It should be upgrade to the last version.
